In [1]:
import numpy as np

# Single Neuron

In [2]:
class Neuron:
    def __init__(self, inputs:int, bias:float = 0):
        self.weights = np.random.rand(1, inputs) # [neurons, inputs]
        self.bias = bias
        
    
    def forward(self, inputs:np.array) -> float:
        return np.dot(inputs, self.weights.T) + self.bias

In [3]:
n = Neuron(4)
n.weights.shape

(1, 4)

In [4]:
data = np.random.randn(5, 1, 4)
data

array([[[-0.21161333,  0.43732363,  0.64967487, -1.46280813]],

       [[ 0.50345284,  1.72607308, -0.88208271,  1.04684912]],

       [[ 0.70630965, -1.54751589, -0.29997737, -2.26351755]],

       [[ 0.96120035,  0.8290234 , -1.12327137,  0.73222665]],

       [[ 1.03781549, -0.68140354, -0.370326  ,  0.47988509]]])

In [5]:
for i, x in enumerate(data):
    print(f"{i+1} - {n.forward(x)}")

1 - [[-0.02810576]]
2 - [[1.09551174]]
3 - [[-1.45522526]]
4 - [[0.58193107]]
5 - [[0.07991762]]


# Layers

In [6]:
class DenseLayer:
    def __init__(self, inputs:int, neurons:int, bias:bool = True):
        self.weights = np.random.rand(neurons, inputs)
        self.bias = np.random.rand(neurons, 1) if bias else np.zeros((neurons, 1))

        
    def forward(self, x:np.array) -> np.array:
        return np.dot(x, self.weights.T) + self.bias.T

In [7]:
dl = DenseLayer(4, 5)
dl.weights

array([[0.01277534, 0.06955301, 0.91127411, 0.8136686 ],
       [0.45378492, 0.90707179, 0.48754689, 0.5396319 ],
       [0.06904036, 0.39138748, 0.64941738, 0.62071875],
       [0.54780858, 0.6965424 , 0.6316497 , 0.26635174],
       [0.56817529, 0.93100393, 0.64562375, 0.95011933]])

In [8]:
dl.bias

array([[0.22609927],
       [0.19710501],
       [0.04100734],
       [0.05485621],
       [0.19950757]])

In [9]:
dl2 = DenseLayer(inputs=4, neurons=5, bias=False)
dl2.weights

array([[0.33303884, 0.93920101, 0.54607873, 0.953397  ],
       [0.06459566, 0.01589727, 0.59733716, 0.82999414],
       [0.5433925 , 0.76766405, 0.06902136, 0.85137328],
       [0.1526616 , 0.24890199, 0.96180459, 0.96153616],
       [0.98403053, 0.50467698, 0.77697733, 0.71932398]])

In [10]:
dl2.bias

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
for x in data:
    print(dl.forward(x))

[[-0.34439615  0.02513103 -0.28852181  0.26429251 -0.48397265]]
[[0.40055374 2.12609301 0.82828832 1.25459789 2.51767589]]
[[-1.98762654 -2.25380965 -2.11572543 -1.42850418 -3.18421242]]
[[-0.13177829  1.23275236  0.15687319  0.64437578  1.48795392]]
[[ 0.24496298  0.12837811 -0.09665679  0.0426559   0.37163616]]


In [12]:
dl.forward(data[0])

array([[-0.34439615,  0.02513103, -0.28852181,  0.26429251, -0.48397265]])

In [13]:
dl1 = DenseLayer(inputs=1, neurons=3)
dl2 = DenseLayer(inputs=3, neurons=7)

In [14]:
dl2.forward(dl1.forward(np.array([1])))

array([[1.14867558, 1.28549987, 2.13585067, 1.70780203, 0.88291409,
        2.14288439, 2.0940898 ]])